project:
  type: website
  output-dir: docs
  resources:
    - encuentros/1-intro-r/intro-r.scss

website:
  #logo: jsm-logo.png
  #repo-url: https://github.com/pablotis/intro-r-quarto/settings/pages
  #repo-actions: [edit, issue]
  navbar:
    logo: img/background-estacion_r_v2.png
    search: true
    left:
      - href: index.qmd
        text: Inicio
      - href: programa.qmd
        text: Programa
      - href: puesta-punto.qmd
        text: Puesta a punto
      - href: profesor.qmd
        text: Docente
    right: 
      - href: cod_de_conducta.qmd
        text: CÃ³digo de conducta
    tools:
      - icon: github
        href: https://github.com/pablotis/intro-r-quarto
 
format:
  html:
    theme: cosmo
    toc: true

editor: visual

execute:
  freeze: auto
